// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8rkVHkk9D3_OmaAwIVezEV1EcgN9o-bU',
    appId: '1:950073164985:web:1f0127cdda83991c968768',
    messagingSenderId: '950073164985',
    projectId: 'fir-tuto-a7b0d',
    authDomain: 'fir-tuto-a7b0d.firebaseapp.com',
    storageBucket: 'fir-tuto-a7b0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVUy0rA8FBKsEHLv9Wx6mL1eo2epIslYI',
    appId: '1:950073164985:android:315e174e80a8076d968768',
    messagingSenderId: '950073164985',
    projectId: 'fir-tuto-a7b0d',
    storageBucket: 'fir-tuto-a7b0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlhS62MnHmea7mgLtZyj3_pfaDeoDjT3w',
    appId: '1:950073164985:ios:d85121d57e9d3846968768',
    messagingSenderId: '950073164985',
    projectId: 'fir-tuto-a7b0d',
    storageBucket: 'fir-tuto-a7b0d.appspot.com',
    iosBundleId: 'com.example.firebasetuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlhS62MnHmea7mgLtZyj3_pfaDeoDjT3w',
    appId: '1:950073164985:ios:3298caf0475c0680968768',
    messagingSenderId: '950073164985',
    projectId: 'fir-tuto-a7b0d',
    storageBucket: 'fir-tuto-a7b0d.appspot.com',
    iosBundleId: 'com.example.firebasetuto.RunnerTests',
  );
}
